// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3FNEB_yVg4Yy_owwx3HjFSjSeZxkZv3c',
    appId: '1:584920959416:web:dbd5ef627da01ef9c3e74d',
    messagingSenderId: '584920959416',
    projectId: 'eatsy-food-delivery-app-7ca89',
    authDomain: 'eatsy-food-delivery-app-7ca89.firebaseapp.com',
    storageBucket: 'eatsy-food-delivery-app-7ca89.appspot.com',
    measurementId: 'G-KQ8VNEQ44B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFumHo3NXXT6j5jSRIbxblCbOhBSIMzOE',
    appId: '1:584920959416:android:6d3607cc2b9feb37c3e74d',
    messagingSenderId: '584920959416',
    projectId: 'eatsy-food-delivery-app-7ca89',
    storageBucket: 'eatsy-food-delivery-app-7ca89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Kq4N1mIIX9z0SyA_WIwoPeSPsys-0DQ',
    appId: '1:584920959416:ios:59e5eb5b6a66e48ec3e74d',
    messagingSenderId: '584920959416',
    projectId: 'eatsy-food-delivery-app-7ca89',
    storageBucket: 'eatsy-food-delivery-app-7ca89.appspot.com',
    iosBundleId: 'com.example.eatsyFoodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Kq4N1mIIX9z0SyA_WIwoPeSPsys-0DQ',
    appId: '1:584920959416:ios:59e5eb5b6a66e48ec3e74d',
    messagingSenderId: '584920959416',
    projectId: 'eatsy-food-delivery-app-7ca89',
    storageBucket: 'eatsy-food-delivery-app-7ca89.appspot.com',
    iosBundleId: 'com.example.eatsyFoodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3FNEB_yVg4Yy_owwx3HjFSjSeZxkZv3c',
    appId: '1:584920959416:web:c596d07b645b4ad5c3e74d',
    messagingSenderId: '584920959416',
    projectId: 'eatsy-food-delivery-app-7ca89',
    authDomain: 'eatsy-food-delivery-app-7ca89.firebaseapp.com',
    storageBucket: 'eatsy-food-delivery-app-7ca89.appspot.com',
    measurementId: 'G-DS3S5RDCW1',
  );
}
